import { sendEmail } from "../lib/email";

async function main() {
  const recipient = "talha.sajid@ultrashaheens.com";
  
  console.log(`🚀 Attempting to send a test email to: ${recipient}...`);
  console.log(`Using Gmail Account: ${process.env.GMAIL_USER}`);

  try {
    const result = await sendEmail({
      to: recipient,
      subject: "Ultra Shaheens - SMTP Connection Test",
      html: `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #7c3aed; border-radius: 12px; max-width: 500px;">
          <h2 style="color: #7c3aed;">Success!</h2>
          <p>This is a direct test from your local environment to verify that your <b>Gmail SMTP</b> settings are correct.</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 12px; color: #666;">Generated by scripts/test-email.ts</p>
        </div>
      `,
      text: "Ultra Shaheens SMTP Test - Success!"
    });

    console.log("✅ Email sent successfully!");
    console.log("Message ID:", result.messageId);
  } catch (error) {
    console.error("❌ Failed to send email.");
    console.error("Error details:", error);
    process.exit(1);
  }
}

main();
